version: '3.8'
services:
  app:
    image: williansebastiao/php:8.1-nginx
    container_name: app
    ports:
      - 8008:80
      - 443:443
    volumes:
      - .:/var/www/app
    networks:
      - ethos
networks:
  ethos:
    driver: bridge