version: '3.8'
services:
  nginx:
    image: williansebastiao/nginx:latest
    container_name: nginx-${APP_ENV}
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www/app
    depends_on:
      - php
      - mysql
    networks:
      - ethos
  php:
    image: williansebastiao/php:8.1
    container_name: php-${APP_ENV}
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/app
    networks:
      - ethos
  mysql:
    image: mysql:8
    container_name: mysql-${APP_ENV}
    ports:
      - 3308:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - ethos
  supervisor:
      image: williansebastiao/supervisor:1.0
      container_name: supervisor-${APP_ENV}
      volumes:
          - .:/var/www/app
      networks:
          - ethos
networks:
  ethos:
    driver: bridge
