version: '3'
services:
  nginx:
    image: ethos/nginx:latest
    container_name: nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
      - php
    networks:
      - ethos
  php:
    image: ethos/php:8
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
    networks:
      - ethos
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3308:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - ethos
networks:
  ethos:
    driver: bridge