apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 3
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
